baseURL = 'https://sdmeyers.github.io/'
languageCode = 'en-us'
title = 'sdmeyers@github'
theme = 'sdm-ghp'
[caches]
    [caches.images]
        dir = ':cacheDir/images'
[params]
        tagline = 'â‡ geeky fun techno babble...'
